const categoryList = {
	// electronics: [
	// 	'https://www.amazon.com/Best-Sellers-Electronics/zgbs/electronics/ref=zg_bs_nav_0',
	// 	'https://www.amazon.com/Best-Sellers/zgbs/amazon-devices/',
	// 	'https://www.amazon.com/Best-Sellers/zgbs/wireless/',
	// 	'https://www.amazon.com/Best-Sellers-Audio-Headphones/zgbs/wireless/172541/',
	// 	'https://www.amazon.com/Best-Sellers-Electronics-Wearable-Technology/zgbs/electronics/10048700011/',
	// 	'https://www.amazon.com/Best-Sellers-Electronics-Video-Game-Consoles-Accessories/zgbs/electronics/7926841011/',
	// 	'https://www.amazon.com/Best-Sellers-Electronics-Cell-Phone-Cases-Holsters-Sleeves/zgbs/electronics/2407760011/',
	// 	'https://www.amazon.com/Best-Sellers-Cell-Phone-Charging-Stations/zgbs/wireless/12557639011/',
	// 	'https://www.amazon.com/Best-Sellers-Electronics-Computer-Monitors/zgbs/electronics/1292115011/',
	// 	'https://www.amazon.com/Best-Sellers-Electronics-Laptop-Computers/zgbs/electronics/565108/',
	// 	'https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Keyboards/zgbs/pc/12879431/',
	// 	'https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Mice/zgbs/pc/11036491/',
	// ],
	// mens: [
	// 	'https://www.amazon.com/Best-Sellers-Mens-Fashion/zgbs/fashion/7147441011/',
	// 	'https://www.amazon.com/Best-Sellers-Mens-Accessories/zgbs/fashion/2474937011/',
	// 	'https://www.amazon.com/Best-Sellers-Mens-Shoes/zgbs/fashion/679255011/',
	// 	'https://www.amazon.com/Best-Sellers-Mens-Watches/zgbs/fashion/6358539011/',
	// 	'https://www.amazon.com/Best-Sellers-Mens-Sunglasses-Eyewear-Accessories/zgbs/fashion/7072330011/',
	// ],
	// womens: [
	// 	'https://www.amazon.com/Best-Sellers-Womens-Fashion/zgbs/fashion/7147440011/',
	// 	'https://www.amazon.com/Best-Sellers-Womens-Accessories/zgbs/fashion/2474936011/',
	// 	'https://www.amazon.com/Best-Sellers-Womens-Sunglasses-Eyewear-Accessories/zgbs/fashion/7072321011/',
	// 	'https://www.amazon.com/Best-Sellers-Womens-Handbags-Purses-Wallets/zgbs/fashion/15743631/',
	// 	'https://www.amazon.com/Best-Sellers-Womens-Shoes/zgbs/fashion/679337011/',
	// 	'https://www.amazon.com/Best-Sellers-Womens-Jewelry/zgbs/fashion/7192394011/',
	// ],
	// baby: [
	// 	'https://www.amazon.com/gp/new-releases/fashion/7147444011/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Nursery-D%C3%A9cor/zgbs/home-garden/166875011/',
	// 	'https://www.amazon.com/Best-Sellers-Baby-Girls-Accessories/zgbs/fashion/2478435011/',
	// 	'https://www.amazon.com/Best-Sellers-Baby-Boys-Accessories/zgbs/fashion/2478436011/',
	// ],
	// homeware: [
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen/zgbs/home-garden/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-D%C3%A9cor-Products/zgbs/home-garden/1063278/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Clocks/zgbs/home-garden/542938/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Furniture/zgbs/home-garden/1063306/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Office-Furniture/zgbs/home-garden/1063312/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Coffee-Tea-Espresso/zgbs/home-garden/915194/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Wine-Accessories/zgbs/home-garden/13299291/',
	// 	'https://www.amazon.com/Best-Sellers-Home-Kitchen-Bar-Tools-Drinkware/zgbs/home-garden/289728',
	// 	'https://www.amazon.com/Best-Sellers-Kitchen-Dining-Beer-Mugs-Steins/zgbs/kitchen/13217761/ref=zg_bs_nav_k_3_289728',
	// ],
	sports: [
		// 'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Running-Equipment/zgbs/sporting-goods/3416071/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Exercise-Fitness-Equipment/zgbs/sporting-goods/3407731/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Snowboarding-Equipment/zgbs/sporting-goods/2342471011/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Outdoor-Recreation/zgbs/sporting-goods/706814011/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Skateboarding-Equipment/zgbs/sporting-goods/3416111/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Electronics-Gadgets/zgbs/sporting-goods/219367011/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Camping-Hiking-Equipment/zgbs/sporting-goods/3400371/',
		'https://www.amazon.com/Best-Sellers-Sports-Outdoors-Hiking-Backpacks-Bags-Accessories/zgbs/sporting-goods/3400391/',
	],
	photography: [
		'https://www.amazon.com/Best-Sellers-Electronics-Digital-Cameras/zgbs/electronics/281052/',
		'https://www.amazon.com/Best-Sellers-Electronics-Camera-Bags-Cases/zgbs/electronics/172437/',
		'https://www.amazon.com/Best-Sellers-Camera-Photo-Camcorders/zgbs/photo/172421/',
	],
}

module.exports = categoryList
